// Code generated by protoc-gen-go. DO NOT EDIT.
// source: innerMap.proto

package innerMap

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Map struct {
	Floor                []*Floor `protobuf:"bytes,1,rep,name=floor,proto3" json:"floor,omitempty"`
	Fill                 []*Fill  `protobuf:"bytes,2,rep,name=fill,proto3" json:"fill,omitempty"`
	Label                []*Label `protobuf:"bytes,3,rep,name=label,proto3" json:"label,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Map) Reset()         { *m = Map{} }
func (m *Map) String() string { return proto.CompactTextString(m) }
func (*Map) ProtoMessage()    {}
func (*Map) Descriptor() ([]byte, []int) {
	return fileDescriptor_586d9d309610c671, []int{0}
}

func (m *Map) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Map.Unmarshal(m, b)
}
func (m *Map) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Map.Marshal(b, m, deterministic)
}
func (m *Map) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Map.Merge(m, src)
}
func (m *Map) XXX_Size() int {
	return xxx_messageInfo_Map.Size(m)
}
func (m *Map) XXX_DiscardUnknown() {
	xxx_messageInfo_Map.DiscardUnknown(m)
}

var xxx_messageInfo_Map proto.InternalMessageInfo

func (m *Map) GetFloor() []*Floor {
	if m != nil {
		return m.Floor
	}
	return nil
}

func (m *Map) GetFill() []*Fill {
	if m != nil {
		return m.Fill
	}
	return nil
}

func (m *Map) GetLabel() []*Label {
	if m != nil {
		return m.Label
	}
	return nil
}

type Floor struct {
	Geometry             []*Geometry   `protobuf:"bytes,1,rep,name=geometry,proto3" json:"geometry,omitempty"`
	Properties           []*Properties `protobuf:"bytes,2,rep,name=properties,proto3" json:"properties,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Floor) Reset()         { *m = Floor{} }
func (m *Floor) String() string { return proto.CompactTextString(m) }
func (*Floor) ProtoMessage()    {}
func (*Floor) Descriptor() ([]byte, []int) {
	return fileDescriptor_586d9d309610c671, []int{1}
}

func (m *Floor) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Floor.Unmarshal(m, b)
}
func (m *Floor) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Floor.Marshal(b, m, deterministic)
}
func (m *Floor) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Floor.Merge(m, src)
}
func (m *Floor) XXX_Size() int {
	return xxx_messageInfo_Floor.Size(m)
}
func (m *Floor) XXX_DiscardUnknown() {
	xxx_messageInfo_Floor.DiscardUnknown(m)
}

var xxx_messageInfo_Floor proto.InternalMessageInfo

func (m *Floor) GetGeometry() []*Geometry {
	if m != nil {
		return m.Geometry
	}
	return nil
}

func (m *Floor) GetProperties() []*Properties {
	if m != nil {
		return m.Properties
	}
	return nil
}

type Fill struct {
	Geometry             []*Geometry   `protobuf:"bytes,1,rep,name=geometry,proto3" json:"geometry,omitempty"`
	Properties           []*Properties `protobuf:"bytes,2,rep,name=properties,proto3" json:"properties,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Fill) Reset()         { *m = Fill{} }
func (m *Fill) String() string { return proto.CompactTextString(m) }
func (*Fill) ProtoMessage()    {}
func (*Fill) Descriptor() ([]byte, []int) {
	return fileDescriptor_586d9d309610c671, []int{2}
}

func (m *Fill) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Fill.Unmarshal(m, b)
}
func (m *Fill) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Fill.Marshal(b, m, deterministic)
}
func (m *Fill) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Fill.Merge(m, src)
}
func (m *Fill) XXX_Size() int {
	return xxx_messageInfo_Fill.Size(m)
}
func (m *Fill) XXX_DiscardUnknown() {
	xxx_messageInfo_Fill.DiscardUnknown(m)
}

var xxx_messageInfo_Fill proto.InternalMessageInfo

func (m *Fill) GetGeometry() []*Geometry {
	if m != nil {
		return m.Geometry
	}
	return nil
}

func (m *Fill) GetProperties() []*Properties {
	if m != nil {
		return m.Properties
	}
	return nil
}

type Label struct {
	Geometry             []*Geometry   `protobuf:"bytes,1,rep,name=geometry,proto3" json:"geometry,omitempty"`
	Properties           []*Properties `protobuf:"bytes,2,rep,name=properties,proto3" json:"properties,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Label) Reset()         { *m = Label{} }
func (m *Label) String() string { return proto.CompactTextString(m) }
func (*Label) ProtoMessage()    {}
func (*Label) Descriptor() ([]byte, []int) {
	return fileDescriptor_586d9d309610c671, []int{3}
}

func (m *Label) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Label.Unmarshal(m, b)
}
func (m *Label) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Label.Marshal(b, m, deterministic)
}
func (m *Label) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Label.Merge(m, src)
}
func (m *Label) XXX_Size() int {
	return xxx_messageInfo_Label.Size(m)
}
func (m *Label) XXX_DiscardUnknown() {
	xxx_messageInfo_Label.DiscardUnknown(m)
}

var xxx_messageInfo_Label proto.InternalMessageInfo

func (m *Label) GetGeometry() []*Geometry {
	if m != nil {
		return m.Geometry
	}
	return nil
}

func (m *Label) GetProperties() []*Properties {
	if m != nil {
		return m.Properties
	}
	return nil
}

type Geometry struct {
	Type                 string      `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Coordinates          [][]float64 `protobuf:"fixed64,2,rep,packed,name=coordinates,proto3" json:"coordinates,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Geometry) Reset()         { *m = Geometry{} }
func (m *Geometry) String() string { return proto.CompactTextString(m) }
func (*Geometry) ProtoMessage()    {}
func (*Geometry) Descriptor() ([]byte, []int) {
	return fileDescriptor_586d9d309610c671, []int{4}
}

func (m *Geometry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Geometry.Unmarshal(m, b)
}
func (m *Geometry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Geometry.Marshal(b, m, deterministic)
}
func (m *Geometry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Geometry.Merge(m, src)
}
func (m *Geometry) XXX_Size() int {
	return xxx_messageInfo_Geometry.Size(m)
}
func (m *Geometry) XXX_DiscardUnknown() {
	xxx_messageInfo_Geometry.DiscardUnknown(m)
}

var xxx_messageInfo_Geometry proto.InternalMessageInfo

func (m *Geometry) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Geometry) GetCoordinates() [][]float64 {
	if m != nil {
		return m.Coordinates
	}
	return nil
}

type Properties struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Icon                 string   `protobuf:"bytes,3,opt,name=icon,proto3" json:"icon,omitempty"`
	X                    float64  `protobuf:"fixed64,4,opt,name=x,proto3" json:"x,omitempty"`
	Y                    float64  `protobuf:"fixed64,5,opt,name=y,proto3" json:"y,omitempty"`
	Floor                int64    `protobuf:"varint,6,opt,name=floor,proto3" json:"floor,omitempty"`
	Height               int64    `protobuf:"varint,7,opt,name=height,proto3" json:"height,omitempty"`
	Base                 string   `protobuf:"bytes,8,opt,name=base,proto3" json:"base,omitempty"`
	Color                string   `protobuf:"bytes,9,opt,name=color,proto3" json:"color,omitempty"`
	Opacity              float32  `protobuf:"fixed32,10,opt,name=opacity,proto3" json:"opacity,omitempty"`
	BorderColor          string   `protobuf:"bytes,11,opt,name=borderColor,proto3" json:"borderColor,omitempty"`
	Layer                float32  `protobuf:"fixed32,12,opt,name=layer,proto3" json:"layer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Properties) Reset()         { *m = Properties{} }
func (m *Properties) String() string { return proto.CompactTextString(m) }
func (*Properties) ProtoMessage()    {}
func (*Properties) Descriptor() ([]byte, []int) {
	return fileDescriptor_586d9d309610c671, []int{5}
}

func (m *Properties) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Properties.Unmarshal(m, b)
}
func (m *Properties) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Properties.Marshal(b, m, deterministic)
}
func (m *Properties) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Properties.Merge(m, src)
}
func (m *Properties) XXX_Size() int {
	return xxx_messageInfo_Properties.Size(m)
}
func (m *Properties) XXX_DiscardUnknown() {
	xxx_messageInfo_Properties.DiscardUnknown(m)
}

var xxx_messageInfo_Properties proto.InternalMessageInfo

func (m *Properties) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Properties) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Properties) GetIcon() string {
	if m != nil {
		return m.Icon
	}
	return ""
}

func (m *Properties) GetX() float64 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Properties) GetY() float64 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *Properties) GetFloor() int64 {
	if m != nil {
		return m.Floor
	}
	return 0
}

func (m *Properties) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *Properties) GetBase() string {
	if m != nil {
		return m.Base
	}
	return ""
}

func (m *Properties) GetColor() string {
	if m != nil {
		return m.Color
	}
	return ""
}

func (m *Properties) GetOpacity() float32 {
	if m != nil {
		return m.Opacity
	}
	return 0
}

func (m *Properties) GetBorderColor() string {
	if m != nil {
		return m.BorderColor
	}
	return ""
}

func (m *Properties) GetLayer() float32 {
	if m != nil {
		return m.Layer
	}
	return 0
}

func init() {
	proto.RegisterType((*Map)(nil), "innerMap.Map")
	proto.RegisterType((*Floor)(nil), "innerMap.Floor")
	proto.RegisterType((*Fill)(nil), "innerMap.Fill")
	proto.RegisterType((*Label)(nil), "innerMap.Label")
	proto.RegisterType((*Geometry)(nil), "innerMap.Geometry")
	proto.RegisterType((*Properties)(nil), "innerMap.Properties")
}

func init() { proto.RegisterFile("innerMap.proto", fileDescriptor_586d9d309610c671) }

var fileDescriptor_586d9d309610c671 = []byte{
	// 355 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x93, 0x4f, 0x6a, 0xeb, 0x30,
	0x10, 0xc6, 0x91, 0xff, 0x24, 0xce, 0x24, 0xe4, 0x81, 0x08, 0x0f, 0x2d, 0x8d, 0xe1, 0x81, 0x57,
	0x59, 0xbc, 0xf6, 0x00, 0x85, 0x42, 0xbb, 0x69, 0xa0, 0xe8, 0x06, 0xb2, 0xad, 0x24, 0x02, 0xd9,
	0x32, 0x8a, 0xa0, 0xf1, 0x15, 0x7a, 0xea, 0x32, 0x92, 0x9d, 0x98, 0x1e, 0x20, 0xbb, 0xf9, 0xbe,
	0x99, 0xef, 0x37, 0x12, 0x48, 0xb0, 0x55, 0x5d, 0x27, 0xed, 0x41, 0xf4, 0xfb, 0xde, 0x1a, 0x67,
	0x68, 0x36, 0xe9, 0xe2, 0x0b, 0xe2, 0x83, 0xe8, 0xe9, 0x3f, 0x48, 0x8f, 0xda, 0x18, 0xcb, 0x48,
	0x1e, 0x97, 0xeb, 0xff, 0x7f, 0xf6, 0xb7, 0xc0, 0x1b, 0xda, 0x3c, 0x74, 0x69, 0x01, 0xc9, 0x51,
	0x69, 0xcd, 0x22, 0x3f, 0xb5, 0x9d, 0x4d, 0x29, 0xad, 0xb9, 0xef, 0x21, 0x4a, 0x8b, 0x4a, 0x6a,
	0x16, 0xff, 0x46, 0x7d, 0xa0, 0xcd, 0x43, 0xb7, 0x68, 0x21, 0xf5, 0x68, 0xba, 0x87, 0xec, 0x24,
	0x4d, 0x2b, 0x9d, 0x1d, 0xc6, 0xed, 0xf4, 0x1e, 0x79, 0x1f, 0x3b, 0xfc, 0x36, 0x43, 0x9f, 0x01,
	0x7a, 0x6b, 0x7a, 0x69, 0x9d, 0x92, 0x97, 0xf1, 0x24, 0xbb, 0x7b, 0xe2, 0xf3, 0xd6, 0xe3, 0xb3,
	0xb9, 0x42, 0x43, 0x82, 0x67, 0x7c, 0xd0, 0xb6, 0x16, 0x52, 0x7f, 0xd9, 0x07, 0xad, 0x7b, 0x81,
	0x6c, 0x62, 0x51, 0x0a, 0x89, 0x1b, 0x7a, 0xc9, 0x48, 0x4e, 0xca, 0x15, 0xf7, 0x35, 0xcd, 0x61,
	0x5d, 0x1b, 0x63, 0x1b, 0xd5, 0x09, 0x37, 0x62, 0x09, 0x9f, 0x5b, 0xc5, 0x77, 0x04, 0x70, 0x87,
	0xd3, 0x2d, 0x44, 0xaa, 0x19, 0x11, 0x91, 0x6a, 0x10, 0xda, 0x89, 0x56, 0xb2, 0x28, 0x40, 0xb1,
	0x46, 0x4f, 0xd5, 0xa6, 0x63, 0x71, 0xf0, 0xb0, 0xa6, 0x1b, 0x20, 0x57, 0x96, 0xe4, 0xa4, 0x24,
	0x9c, 0x5c, 0x51, 0x0d, 0x2c, 0x0d, 0x6a, 0xa0, 0xbb, 0xe9, 0x89, 0x2d, 0x72, 0x52, 0xc6, 0xd3,
	0x8b, 0xfa, 0x0b, 0x8b, 0xb3, 0x54, 0xa7, 0xb3, 0x63, 0x4b, 0x6f, 0x8f, 0x0a, 0xe9, 0x95, 0xb8,
	0x48, 0x96, 0x05, 0x3a, 0xd6, 0x48, 0xa8, 0x8d, 0x36, 0x96, 0xad, 0xbc, 0x19, 0x04, 0x65, 0xb0,
	0x34, 0xbd, 0xa8, 0x95, 0x1b, 0x18, 0xe4, 0xa4, 0x8c, 0xf8, 0x24, 0xf1, 0xda, 0x95, 0xb1, 0x8d,
	0xb4, 0xaf, 0x3e, 0xb5, 0xf6, 0xa9, 0xb9, 0x85, 0x44, 0x2d, 0x06, 0x69, 0xd9, 0xc6, 0x27, 0x83,
	0xa8, 0x16, 0xfe, 0x93, 0x3c, 0xfd, 0x04, 0x00, 0x00, 0xff, 0xff, 0x05, 0x1a, 0xb2, 0xda, 0x36,
	0x03, 0x00, 0x00,
}
